export const sampleStudents = [
  {
    id: "S-2026-0317",
    name: "张三",
    grade: "11年级 · A-Level",
    servicePort: "学管 / 学科 / 规划",
    updatedAt: "2026-08-06T10:30:00+08:00",
    workflowStatus: "AI预警未核实",
    previousRiskLevel: "中",
    dataAvailability: {
      chat: true, attendance: true, homework: true, mock: true, planning: true,
      reply: true, monthlyCommunication: true, courseConsumption: true,
      finance: false, complaintHistory: true,
    },
    relationship: {
      signals: [
        {
          id: "signal-change-teacher",
          type: "change_teacher",
          title: "家长出现换师倾向",
          summary: "家长对当前教学和沟通结果表达明确不满，并提及更换老师。",
          quote: "如果还是这样，我想换个老师。",
          source: "家长反馈群 · 企微",
          occurredAt: "2026-08-04T19:42:00+08:00",
          confidence: "高",
          verified: false,
          sensitiveFor: [],
        },
        {
          id: "signal-planner-style",
          type: "negative_style",
          title: "规划沟通风格被质疑",
          summary: "家长向顾问反馈规划师推进力度不足，希望更主动地PUSH学生。",
          quote: "能不能请规划老师再push一点？现在感觉有点太温和了。",
          source: "顾问私聊 · 企微",
          occurredAt: "2026-08-01T15:20:00+08:00",
          confidence: "中",
          verified: false,
          sensitiveFor: ["advisor", "planner"],
        },
      ],
    },
    learning: {
      attendanceRate: 0.7,
      homeworkSubmitRate: 0.6,
      homeworkOverdueRate: 0.3,
      homeworkTrend: -0.04,
      mockTrend: -0.062,
      updatedAt: "2026-08-05T22:00:00+08:00",
    },
    planning: {
      overdueDays: 10,
      nodeName: "个人陈述素材初稿",
      updatedAt: "2026-08-03T09:00:00+08:00",
    },
    service: {
      overdueReplyCount: 2,
      averageReplyHours: 18,
      maxReplyHours: 31,
      monthlyCommunicationRate: 1,
      scheduleProcessingHours: 18,
      updatedAt: "2026-08-02T20:00:00+08:00",
    },
    financial: {
      refundRate: 0,
      consumedHours: 18,
      scoreLiftPerHour: 0.0008,
      updatedAt: "2026-08-05T08:00:00+08:00",
    },
    history: {
      complaintCount: 1,
      lastComplaintAt: "2025-11-20T12:00:00+08:00",
    },
    extraEvents: [
      {
        id: "absence-event",
        occurredAt: "2026-07-29T14:00:00+08:00",
        title: "学生缺勤一节数学课",
        detail: "缺勤未提前说明，学管已在群内询问。",
        source: "唯寻工作台 · 出勤记录",
      },
    ],
  },
  {
    id: "S-2026-0188",
    name: "李宁",
    grade: "10年级 · IGCSE",
    servicePort: "学管 / 学科",
    updatedAt: "2026-08-06T09:45:00+08:00",
    workflowStatus: "AI预警未核实",
    previousRiskLevel: "低",
    dataAvailability: {
      chat: true, attendance: true, homework: true, mock: true, planning: false,
      reply: true, monthlyCommunication: true, courseConsumption: true,
      finance: true, complaintHistory: true,
    },
    relationship: { signals: [] },
    learning: {
      attendanceRate: 0.82,
      homeworkSubmitRate: 0.65,
      homeworkOverdueRate: 0.35,
      homeworkTrend: -0.01,
      mockTrend: -0.02,
      updatedAt: "2026-08-05T19:00:00+08:00",
    },
    planning: {},
    service: {
      overdueReplyCount: 1,
      averageReplyHours: 15,
      maxReplyHours: 28,
      monthlyCommunicationRate: 0.5,
      scheduleProcessingHours: 12,
      updatedAt: "2026-08-04T16:00:00+08:00",
    },
    financial: {
      refundRate: 0,
      consumedHours: 8,
      scoreLiftPerHour: 0.004,
      updatedAt: "2026-08-05T08:00:00+08:00",
    },
    history: { complaintCount: 0, lastComplaintAt: null },
    extraEvents: [],
  },
  {
    id: "S-2026-0421",
    name: "王悦",
    grade: "9年级 · 国际学校",
    servicePort: "学管 / 规划",
    updatedAt: "2026-08-06T08:20:00+08:00",
    workflowStatus: "已解除",
    previousRiskLevel: "低",
    dataAvailability: {
      chat: true, attendance: true, homework: true, mock: true, planning: true,
      reply: true, monthlyCommunication: true, courseConsumption: true,
      finance: true, complaintHistory: true,
    },
    relationship: { signals: [] },
    learning: {
      attendanceRate: 0.96,
      homeworkSubmitRate: 0.94,
      homeworkOverdueRate: 0.05,
      homeworkTrend: 0.025,
      mockTrend: 0.018,
      updatedAt: "2026-08-05T18:00:00+08:00",
    },
    planning: { overdueDays: 0, nodeName: "九年级规划复盘", updatedAt: "2026-08-03T09:00:00+08:00" },
    service: {
      overdueReplyCount: 0,
      averageReplyHours: 3,
      maxReplyHours: 6,
      monthlyCommunicationRate: 1,
      scheduleProcessingHours: 8,
      updatedAt: "2026-08-04T12:00:00+08:00",
    },
    financial: { refundRate: 0, consumedHours: 6, scoreLiftPerHour: 0.006, updatedAt: "2026-08-05T08:00:00+08:00" },
    history: { complaintCount: 0, lastComplaintAt: null },
    extraEvents: [
      {
        id: "positive-feedback",
        occurredAt: "2026-08-03T20:00:00+08:00",
        title: "家长确认近期安排",
        detail: "家长回复已了解，并认可下阶段计划。",
        source: "家长反馈群 · 企微",
      },
    ],
  },
  {
    id: "S-2026-0509",
    name: "陈默",
    grade: "12年级 · A-Level",
    servicePort: "新交接",
    updatedAt: "2026-08-06T07:50:00+08:00",
    workflowStatus: "AI预警未核实",
    previousRiskLevel: null,
    dataAvailability: {
      chat: false, attendance: false, homework: false, mock: false, planning: true,
      reply: false, monthlyCommunication: false, courseConsumption: true,
      finance: true, complaintHistory: false,
    },
    relationship: { signals: [] },
    learning: {},
    planning: { overdueDays: 0, nodeName: "申请材料交接", updatedAt: "2026-08-05T09:00:00+08:00" },
    service: { scheduleProcessingHours: 10, updatedAt: "2026-08-05T09:00:00+08:00" },
    financial: { refundRate: 0, consumedHours: 2, scoreLiftPerHour: null, updatedAt: "2026-08-05T08:00:00+08:00" },
    history: { complaintCount: 0, lastComplaintAt: null },
    extraEvents: [],
  },
];
